# Generated by Django 5.0.3 on 2024-03-09 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='W_materials', to='product.material'),
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PM_materials', to='product.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PM_product', to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_material',
        ),
    ]
