# Generated by Django 5.0.3 on 2024-03-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_warehouse_material_productmaterial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
